# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "ahci"
    "xhci_pci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ "usb_storage" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/7d5c0dfc-4040-4576-8c1b-5d77520f223b";
    fsType = "btrfs";
    options = [
      "noatime"
      "compress=zstd"
      "subvol=root"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/7d5c0dfc-4040-4576-8c1b-5d77520f223b";
    fsType = "btrfs";
    options = [
      "noatime"
      "compress=zstd"
      "subvol=home"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/7d5c0dfc-4040-4576-8c1b-5d77520f223b";
    fsType = "btrfs";
    options = [
      "noatime"
      "compress=zstd"
      "subvol=nix"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/9620-4CE1";
    fsType = "vfat";
  };

  #fileSystems."/home/arne/.cache" =
  #  { device = "tmpfs";
  #    fsType = "tmpfs";
  #    options = [ "uid=1000" "gid=100"];
  #  };

  #fileSystems."/run/LUKS_keys_mount" =
  #  { device = "/dev/disk/by-uuid/42a06aec-f0b7-4cdd-a334-2a3436124a39";
  #    options = [ "nofail" ];
  #  };

  #boot.initrd.luks.devices.home3 = {
  #  device = "/dev/disk/by-uuid/b3a76078-cb47-45c8-91a3-ab64716c80d7";
  #  allowDiscards = true;
  #  fallbackToPassword = false;
  #  keyFile = "/mnt-root/run/LUKS_keys/home.key";
  #};

  #fileSystems."/home3" =
  #  { device = "/dev/mapper/home3";
  #  };

  swapDevices = [ ];
  #  [ { device = "/dev/disk/by-uuid/89b93505-a8bb-4d82-9683-e24223c31c5d"; }
  #  ];

}
